/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JFrame;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.Timer;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import controller.CirculationController;
import model.Circulation;
import util.Session;
/**
 *
 * @author A
 */
public class CirculationPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CirculationPage.class.getName());
    private CirculationController cc = new CirculationController();

    /**
     * Creates new form Dash_Board
     */
    public CirculationPage() {
    initComponents();
    fullname.setText(Session.getFullName());
    position.setText(Session.getRole().toUpperCase());
    allCirculationsTable();
    startClock();
    setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    
    // Escape key to clear selection
    circulationTable.getInputMap(javax.swing.JComponent.WHEN_FOCUSED)
        .put(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0), "clearSelection");
    circulationTable.getActionMap().put("clearSelection", new javax.swing.AbstractAction() {
        @Override public void actionPerformed(java.awt.event.ActionEvent e) { circulationTable.clearSelection(); }
    });
    
    // Right-click to clear selection
    circulationTable.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            if (javax.swing.SwingUtilities.isRightMouseButton(evt)) { circulationTable.clearSelection(); }
        }
    });
}

private void startClock() {
    Timer timer = new Timer(1000, e -> {
        LocalDateTime now = LocalDateTime.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("MMMM dd, yyyy  hh:mm:ss a");
        dateTimeLabel.setText(now.format(formatter));
    });
    timer.start();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        menupanel = new javax.swing.JPanel();
        resource_panel = new javax.swing.JPanel();
        return_panel = new javax.swing.JPanel();
        member_panel = new javax.swing.JPanel();
        staff_panel = new javax.swing.JPanel();
        staff = new javax.swing.JLabel();
        members = new javax.swing.JLabel();
        returns = new javax.swing.JLabel();
        resource = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        log = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        dateTimeLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        user = new javax.swing.JLabel();
        fullname = new javax.swing.JLabel();
        position = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        overdue_button = (javax.swing.JButton) new rounded_buttons(20, Color.BLACK); overdue_button.setOpaque(false);
        returnfunc_button = (javax.swing.JButton) new rounded_buttons(20, Color.BLACK); returnfunc_button.setOpaque(false);
        borrow_button = (javax.swing.JButton) new rounded_buttons(20, Color.BLACK); borrow_button.setOpaque(false);
        fines_button = (javax.swing.JButton) new rounded_buttons(20, Color.BLACK); fines_button.setOpaque(false);
        all_button = (javax.swing.JButton) new rounded_buttons(20, Color.BLACK); all_button.setOpaque(false);
        jLabel14 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        circulationTable = new javax.swing.JTable();
        jPanel18 = new javax.swing.JPanel();
        searchbar = new javax.swing.JTextField();
        search_button = (javax.swing.JButton) new rounded_buttons(20, Color.BLACK); search_button.setOpaque(false);
        jPanel17 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menupanel.setBackground(new java.awt.Color(0, 0, 0));

        resource_panel.setBackground(new java.awt.Color(0, 0, 0));

        return_panel.setBackground(new java.awt.Color(255, 255, 255));

        member_panel.setBackground(new java.awt.Color(0, 0, 0));

        staff_panel.setBackground(new java.awt.Color(0, 0, 0));

        staff.setBackground(new java.awt.Color(0, 0, 0));
        staff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/staff white.png"))); // NOI18N
        staff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                staffMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout staff_panelLayout = new javax.swing.GroupLayout(staff_panel);
        staff_panel.setLayout(staff_panelLayout);
        staff_panelLayout.setHorizontalGroup(
            staff_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staff_panelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(staff)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        staff_panelLayout.setVerticalGroup(
            staff_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, staff_panelLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(staff)
                .addGap(39, 39, 39))
        );

        members.setBackground(new java.awt.Color(0, 0, 0));
        members.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/member white.png"))); // NOI18N
        members.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                membersMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout member_panelLayout = new javax.swing.GroupLayout(member_panel);
        member_panel.setLayout(member_panelLayout);
        member_panelLayout.setHorizontalGroup(
            member_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(staff_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(member_panelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(members)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        member_panelLayout.setVerticalGroup(
            member_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, member_panelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(members)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(staff_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        returns.setBackground(new java.awt.Color(0, 0, 0));
        returns.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/return black.png"))); // NOI18N
        returns.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout return_panelLayout = new javax.swing.GroupLayout(return_panel);
        return_panel.setLayout(return_panelLayout);
        return_panelLayout.setHorizontalGroup(
            return_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(member_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(return_panelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(returns)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        return_panelLayout.setVerticalGroup(
            return_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, return_panelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(returns)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(member_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        resource.setBackground(new java.awt.Color(0, 0, 0));
        resource.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/book white.png"))); // NOI18N
        resource.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resourceMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout resource_panelLayout = new javax.swing.GroupLayout(resource_panel);
        resource_panel.setLayout(resource_panelLayout);
        resource_panelLayout.setHorizontalGroup(
            resource_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(return_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(resource_panelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(resource)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        resource_panelLayout.setVerticalGroup(
            resource_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resource_panelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(resource)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(return_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo white.png"))); // NOI18N
        logo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoMouseClicked(evt);
            }
        });

        log.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/log out white.png"))); // NOI18N
        log.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout menupanelLayout = new javax.swing.GroupLayout(menupanel);
        menupanel.setLayout(menupanelLayout);
        menupanelLayout.setHorizontalGroup(
            menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(resource_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(menupanelLayout.createSequentialGroup()
                .addGroup(menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menupanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(logo))
                    .addGroup(menupanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(log)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        menupanelLayout.setVerticalGroup(
            menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menupanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(logo)
                .addGap(62, 62, 62)
                .addComponent(resource_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(log)
                .addContainerGap(269, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        dateTimeLabel.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        dateTimeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addComponent(dateTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dateTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1418, 6, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profile.png"))); // NOI18N
        jPanel3.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 40));

        fullname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        fullname.setText("EDQUIBAL, Christian Mark B.");
        jPanel3.add(fullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        position.setText("ADMIN");
        jPanel3.add(position, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        title.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        title.setText("CIRCULATION");
        jPanel2.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 40, -1, -1));

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));

        overdue_button.setBackground(new java.awt.Color(0, 0, 0));
        overdue_button.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        overdue_button.setForeground(new java.awt.Color(255, 255, 255));
        overdue_button.setText("OVERDUE");
        overdue_button.addActionListener(this::overdue_buttonActionPerformed);

        returnfunc_button.setBackground(new java.awt.Color(0, 0, 0));
        returnfunc_button.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        returnfunc_button.setForeground(new java.awt.Color(255, 255, 255));
        returnfunc_button.setText("RETURN");
        returnfunc_button.addActionListener(this::returnfunc_buttonActionPerformed);

        borrow_button.setBackground(new java.awt.Color(0, 0, 0));
        borrow_button.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        borrow_button.setForeground(new java.awt.Color(255, 255, 255));
        borrow_button.setText("BORROW");
        borrow_button.addActionListener(this::borrow_buttonActionPerformed);

        fines_button.setBackground(new java.awt.Color(0, 0, 0));
        fines_button.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        fines_button.setForeground(new java.awt.Color(255, 255, 255));
        fines_button.setText("FINES");
        fines_button.addActionListener(this::fines_buttonActionPerformed);

        all_button.setBackground(new java.awt.Color(0, 0, 0));
        all_button.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        all_button.setForeground(new java.awt.Color(255, 255, 255));
        all_button.setText("ALL");
        all_button.addActionListener(this::all_buttonActionPerformed);

        jLabel14.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel14.setText("ACTIONS");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(borrow_button, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(returnfunc_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(overdue_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fines_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(all_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(67, 67, 67))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(all_button, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(borrow_button, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(returnfunc_button, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(overdue_button, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fines_button, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));

        circulationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "CIRCULATION ID", "BARCODE", "MEMBER ID", "BORROWED AT", "DUE DATE", "RETURNED", "STATUS", "FINE AMOUNT", "REASON", "PAID", "PROCESSED BY"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(circulationTable);

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));

        search_button.setBackground(new java.awt.Color(0, 0, 0));
        search_button.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        search_button.setForeground(new java.awt.Color(255, 255, 255));
        search_button.setText("SEARCH");
        search_button.addActionListener(this::search_buttonActionPerformed);

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchbar, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(search_button, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchbar, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(search_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(1180, 1180, 1180)
                        .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1575, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 34, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addGap(0, 7, Short.MAX_VALUE)
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 779, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
        );

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 213, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(menupanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menupanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 1011));

        getContentPane().add(jPanel4, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resourceMouseClicked(java.awt.event.MouseEvent evt) {
        ResourcePage rp = new ResourcePage();
        rp.setVisible(true);
        this.dispose();
    }

    private void returnsMouseClicked(java.awt.event.MouseEvent evt) {
        // Already on CirculationPage
    }

    private void membersMouseClicked(java.awt.event.MouseEvent evt) {
        MembersPage mp = new MembersPage();
        mp.setVisible(true);
        this.dispose();
    }

    private void staffMouseClicked(java.awt.event.MouseEvent evt) {
        StaffPage a = new StaffPage();
        a.setVisible(true);
        this.dispose();
    }

    private void logMouseClicked(java.awt.event.MouseEvent evt) {
        Log_In l = new Log_In();
        l.setVisible(true);
        this.dispose();
    }

    private void logoMouseClicked(java.awt.event.MouseEvent evt) {
         Dash_Board a = new Dash_Board();
        a.setVisible(true);
        this.dispose();
    }

    // ==================== CRUD Actions ====================

    private void borrow_buttonActionPerformed(java.awt.event.ActionEvent evt) {
        borrow_form bf = new borrow_form(this);
        bf.setVisible(true);
    }

    private void returnfunc_buttonActionPerformed(java.awt.event.ActionEvent evt) {
        int row = circulationTable.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Please select a circulation record to return.");
            return;
        }
        int circulationId = (int) circulationTable.getValueAt(row, 0);
        String status = String.valueOf(circulationTable.getValueAt(row, 6));
        
        if ("RETURNED".equalsIgnoreCase(status)) {
            JOptionPane.showMessageDialog(this, "This item has already been returned.");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
            "Confirm return for Circulation ID: " + circulationId + "?",
            "Confirm Return", JOptionPane.YES_NO_OPTION);
        
        if (confirm == JOptionPane.YES_OPTION) {
            boolean success = cc.returnCopy(circulationId);
            if (success) {
                added_notification a = new added_notification();
                a.setVisible(true);
                allCirculationsTable();
            } else {
                JOptionPane.showMessageDialog(this, "Return failed.");
            }
        }
    }

    private void overdue_buttonActionPerformed(java.awt.event.ActionEvent evt) {
        loadTable(cc.getOverdue());
    }

    private void all_buttonActionPerformed(java.awt.event.ActionEvent evt) {
        allCirculationsTable();
    }

    private void fines_buttonActionPerformed(java.awt.event.ActionEvent evt) {
        int row = circulationTable.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Please select a circulation record to manage fines.");
            return;
        }
        int circulationId = (int) circulationTable.getValueAt(row, 0);
        Circulation c = cc.getById(circulationId);
        if (c != null) {
            fine_form ff = new fine_form(this, c);
            ff.setVisible(true);
        }
    }

    private void search_buttonActionPerformed(java.awt.event.ActionEvent evt) {
        String keyword = searchbar.getText().trim();
        if (keyword.isEmpty()) {
            allCirculationsTable();
        } else {
            loadTable(cc.search(keyword));
        }
    }

    // ==================== Table Methods ====================

    public void allCirculationsTable() {
        loadTable(cc.getAllCirculations());
    }

    private void loadTable(List<Circulation> list) {
        try {
            DefaultTableModel model = (DefaultTableModel) circulationTable.getModel();
            model.setRowCount(0);
            if (list != null) {
                for (Circulation c : list) {
                    model.addRow(new Object[]{
                        c.getCirculationId(),
                        c.getBarcode(),
                        c.getMemberId(),
                        c.getBorrowedAt() != null ? c.getBorrowedAt().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm")) : "",
                        c.getDueDate() != null ? c.getDueDate().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm")) : "",
                        c.getReturned() != null ? c.getReturned().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm")) : "",
                        c.getStatus() != null ? c.getStatus().name() : "",
                        c.getFineAmount(),
                        c.getReason() != null ? c.getReason().name() : "",
                        c.isPaid() ? "Yes" : "No",
                        c.getProcessedBy()
                    });
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CirculationPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton all_button;
    private javax.swing.JButton borrow_button;
    private javax.swing.JTable circulationTable;
    private javax.swing.JLabel dateTimeLabel;
    private javax.swing.JButton fines_button;
    private javax.swing.JLabel fullname;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel log;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel member_panel;
    private javax.swing.JLabel members;
    private javax.swing.JPanel menupanel;
    private javax.swing.JButton overdue_button;
    private javax.swing.JLabel position;
    private javax.swing.JLabel resource;
    private javax.swing.JPanel resource_panel;
    private javax.swing.JPanel return_panel;
    private javax.swing.JButton returnfunc_button;
    private javax.swing.JLabel returns;
    private javax.swing.JButton search_button;
    private javax.swing.JTextField searchbar;
    private javax.swing.JLabel staff;
    private javax.swing.JPanel staff_panel;
    private javax.swing.JLabel title;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
