/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author A
 */
import java.awt.Color;
public class Sign_Up extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Sign_Up.class.getName());

    /**
     * Creates new form OKAY
     */
    public Sign_Up() {
        initComponents();
        passwords.setEchoChar((char) 0);
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jLabel3 = new javax.swing.JLabel();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = (javax.swing.JPanel) new RoundedPanel(40, Color.BLACK); jPanel3.setOpaque(false);
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Emails = new javax.swing.JTextField();
        UsernNames = new javax.swing.JTextField();
        SignUp2 = new javax.swing.JButton();
        MiddleInitial = new javax.swing.JTextField();
        spcb = new javax.swing.JCheckBox();
        passwords = new javax.swing.JPasswordField();
        Surname = new javax.swing.JTextField();
        FirstName = new javax.swing.JTextField();
        jPanel2 = (javax.swing.JPanel) new RoundedPanel(40, Color.WHITE); jPanel2.setOpaque(false);
        ;
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        SignIn2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, -1, -1));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setBorder(new javax.swing.border.EmptyBorder(10, 10, 10, 10));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sign Up");

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Please provide your credentials to sign up.");

        Emails.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        Emails.setText("Email");
        Emails.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EmailsFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                EmailsFocusLost(evt);
            }
        });

        UsernNames.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        UsernNames.setText("Username");
        UsernNames.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                UsernNamesFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                UsernNamesFocusLost(evt);
            }
        });

        SignUp2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        SignUp2.setText("SIGN UP");
        SignUp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUp2ActionPerformed(evt);
            }
        });

        MiddleInitial.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        MiddleInitial.setText("M.I");
        MiddleInitial.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                MiddleInitialFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                MiddleInitialFocusLost(evt);
            }
        });
        MiddleInitial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MiddleInitialMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MiddleInitialMouseExited(evt);
            }
        });
        MiddleInitial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiddleInitialActionPerformed(evt);
            }
        });

        spcb.setBackground(new java.awt.Color(0, 0, 0));
        spcb.setForeground(new java.awt.Color(255, 255, 255));
        spcb.setSelected(true);
        spcb.setText("Show password");
        spcb.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        spcb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spcbActionPerformed(evt);
            }
        });

        passwords.setText("Password");
        passwords.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordsFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordsFocusLost(evt);
            }
        });
        passwords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordsActionPerformed(evt);
            }
        });

        Surname.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        Surname.setText("Surname");
        Surname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SurnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                SurnameFocusLost(evt);
            }
        });
        Surname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SurnameMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SurnameMouseExited(evt);
            }
        });
        Surname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SurnameActionPerformed(evt);
            }
        });
        Surname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SurnameKeyPressed(evt);
            }
        });

        FirstName.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        FirstName.setText("First Name");
        FirstName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FirstNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                FirstNameFocusLost(evt);
            }
        });
        FirstName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FirstNameMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FirstNameMouseExited(evt);
            }
        });
        FirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(jLabel1)))
                .addContainerGap(133, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SignUp2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(174, 174, 174))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(spcb)
                            .addComponent(UsernNames, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                            .addComponent(passwords, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Emails, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(80, 80, 80))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(Surname, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MiddleInitial, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MiddleInitial, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Surname, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(Emails, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(UsernNames, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passwords, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(spcb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SignUp2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 200, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1023, 660));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 28)); // NOI18N
        jLabel4.setText("LIBRARY MANAGEMENT ");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel5.setText("SYSTEM");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, -1, -1));

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel6.setText("Already have Account? Sign In Now.");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 478, -1, -1));

        SignIn2.setBackground(new java.awt.Color(0, 0, 0));
        SignIn2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        SignIn2.setForeground(new java.awt.Color(255, 255, 255));
        SignIn2.setText("SIGN IN");
        SignIn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignIn2ActionPerformed(evt);
            }
        });
        jPanel2.add(SignIn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 515, 149, 35));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        jLabel7.setFont(new java.awt.Font("Georgia", 1, 48)); // NOI18N
        jLabel7.setText("OOKEEPR ™");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 330, -1));

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 534, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SignUp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUp2ActionPerformed
        Log_In l = new Log_In();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SignUp2ActionPerformed

    private void spcbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spcbActionPerformed
        if (spcb.isSelected()) {
        passwords.setEchoChar((char) 0); // Shows password
    } else {
        passwords.setEchoChar('•'); // Hides password
    }
    }//GEN-LAST:event_spcbActionPerformed

    private void MiddleInitialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MiddleInitialMouseClicked
        
    }//GEN-LAST:event_MiddleInitialMouseClicked

    private void EmailsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmailsFocusGained
        if (Emails.getText().equals("Email")) {
            Emails.setText("");
    }
    }//GEN-LAST:event_EmailsFocusGained

    private void UsernNamesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UsernNamesFocusGained
        if (UsernNames.getText().equals("Username")) {
            UsernNames.setText("");
    }
    }//GEN-LAST:event_UsernNamesFocusGained

    private void passwordsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordsFocusGained

        if (String.valueOf(passwords.getPassword()).equals("Password")) {
        passwords.setText("");
        passwords.setEchoChar('•');
    }
    }//GEN-LAST:event_passwordsFocusGained

    private void SignIn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignIn2ActionPerformed
        Log_In a = new Log_In();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SignIn2ActionPerformed

    private void passwordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordsActionPerformed

    private void MiddleInitialFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MiddleInitialFocusLost
        if (String.valueOf(MiddleInitial.getText()).isEmpty()) {
        MiddleInitial.setText("M.I");
    }
    }//GEN-LAST:event_MiddleInitialFocusLost

    private void passwordsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordsFocusLost
        if (String.valueOf(passwords.getPassword()).isEmpty()) {
        passwords.setText("Password");
        passwords.setEchoChar((char) 0);
    }
    }//GEN-LAST:event_passwordsFocusLost

    private void MiddleInitialMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MiddleInitialMouseExited
      
    }//GEN-LAST:event_MiddleInitialMouseExited

    private void MiddleInitialFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MiddleInitialFocusGained
            if (MiddleInitial.getText().equals("M.I")) {
            MiddleInitial.setText("");
    }
    }//GEN-LAST:event_MiddleInitialFocusGained

    private void SurnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SurnameFocusGained
       
    }//GEN-LAST:event_SurnameFocusGained

    private void SurnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SurnameFocusLost
        if (String.valueOf(Surname.getText()).isEmpty()) {
        Surname.setText("Surname");
        }
    }//GEN-LAST:event_SurnameFocusLost

    private void SurnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SurnameMouseClicked
       if(Surname.getText().equals("Surname")) {
           Surname.setText("");
       }
    }//GEN-LAST:event_SurnameMouseClicked

    private void SurnameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SurnameMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_SurnameMouseExited

    private void FirstNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FirstNameFocusGained
            if(FirstName.getText().equals("First Name")) {
           FirstName.setText("");
       }
    }//GEN-LAST:event_FirstNameFocusGained

    private void FirstNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FirstNameFocusLost
        if (FirstName.getText().isEmpty()) {
        FirstName.setText("First Name");
    }
    }//GEN-LAST:event_FirstNameFocusLost

    private void FirstNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FirstNameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstNameMouseClicked

    private void FirstNameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FirstNameMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstNameMouseExited

    private void MiddleInitialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiddleInitialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MiddleInitialActionPerformed

    private void FirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstNameActionPerformed

    private void SurnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SurnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SurnameActionPerformed

    private void EmailsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmailsFocusLost
       if (Emails.getText().isEmpty()) {
        Emails.setText("Email");
    }
    }//GEN-LAST:event_EmailsFocusLost

    private void UsernNamesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UsernNamesFocusLost
        if (UsernNames.getText().isEmpty()) {
        UsernNames.setText("Username");
    }
    }//GEN-LAST:event_UsernNamesFocusLost

    private void SurnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SurnameKeyPressed
        if (Surname.getText().equals("Surname")) {
        Surname.setText("");
    }
    }//GEN-LAST:event_SurnameKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Sign_Up().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Emails;
    private javax.swing.JTextField FirstName;
    private javax.swing.JTextField MiddleInitial;
    private javax.swing.JButton SignIn2;
    private javax.swing.JButton SignUp2;
    private javax.swing.JTextField Surname;
    private javax.swing.JTextField UsernNames;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField passwords;
    private javax.swing.JCheckBox spcb;
    // End of variables declaration//GEN-END:variables
}
